language: node_js
dist: trusty
sudo: false
node_js:
  - '8'
cache: npm
script:
  - npm run test
  - npm run build
  - pwd && ls
deploy:
  - provider: gcs
    access_key_id: GOOGI7DAF2KATQLNX6L4YLTD
    secret_access_key:
      secure: L2txzEIZxiyeBXCZ/Vy+Q0nAtwfSJxkkJRAlmgm9ykAiCt5aeGHJBRfV5iNtvkqik1hihj1t7cU288mZBpH+hufOfx6ze7TYuIa/1i/IQ226uI2pZL8ORL73hGSgpRPSs4RSCspqTShAsuvLQpdRFV99tYb20NCzFqJgCgkaAXraFokNnsFheTr1BX/hb29qhOK86pL8GfxGtSfllr+2kpUEQqYa4COuLfluB0/U/XUetk7m0pXzB8YzvPcA9WZBjnaR9rdvU6B6bJRaJWVDbbokT9FLOvSApxuuFVmCvGxv+JrqIWGdzYSd3Tw4JbbTNolzNfeqZVvtuyAhVkNS8MT1IgAQAuWLG6NWE8jj7wl0arBSmh06wRfa2MP/Gs/sJL0OCOkHc7uXRmZ4u60m+dGNNRPBYevj4g2quy0nlhy3fEX5+DgrCquijG6Ksdy8rAZJ1G26Tc5cWZno8sl4LgPkaAit7j6llK3W626vdA2jbJpTSjhqXdv1euzt36KzxgiGeV/KfEovKSAGMiaLoFNNAxXaY3OjxcNkq1nOV2C8Drz+4CCEdDxDPabHBFbGIwlGvB55qxC/JDDTs4gRa1R5YEQQU7sCnPq/lb3I62c8fxqLyoXC7smlvukEwoLKbWxYlLTVZCYtw1Xoy7szYajwcpzO3H40Ma1g+3ZV4FM=
    bucket: '$NODE_BUCKET_NAME'
    skip_cleanup: true
    local-dir: dist
    cache_control: public, max-age=3600
    on:
      all_branches: true
      condition: '$TRAVIS_BRANCH =~ ^(master|release.*)$'
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      all_branches: true
notifications:
  slack:
    on_success: never
    rooms:
      - hackforplay:3ZXJmUzsYmjM86Ty3oXOvqpC
env:
  matrix:
    - NODE_ASSET_VERSION='beta-10'
  global:
    - secure: mJ8NHXICkjJRYmZQQHMlx9azXq0Y3KcpRx+J1GjZwfH+45Fkxd1BzOZVhLC5Ct7+tTW1u0NoehOvqLB0xSeZanvH+D+dq+HY0Kykj67EOvb4nB74oQZqXtlAoroC/d/th4aRj52BptCHtxVSwABheTqiDIDWEF5XrmXG0qfVr6sifVIcKTAQc9Ac1yb9AE7J2UBCdsikUigApIX1G343u0JnNE2OvsN3ruDFN3CBoCGXH9bsJqG9T3/FsaKSBsIio9x34daRwFUXP0p0Im0usjJUVrlT1F2xP8ITYmw7jeODbBQAkiW048AKh2nlUg5lCvqA7tbOsW047rr7Zz4e12ZeediEsaFgNeEOKlFzNL15sgzP3i2tkq/avxIR58L9y4oF/rj54fOIuYehfFTi3UQt5hfJCSWb6q9Wcjx3xU7e3KFOHakQgvnSNtOh6deYzmtCBViHObGpd+OReW+3zqmAtiDYKaSHp173XK8Fure0mTwrd/ImTZVTvog2rI0K6NSYx1JLGdqJSdKiu+MGukfhIgJqcFl2kXQt1NRM7aydMkBSKVnKF+GiohfH4SBH/rohf7YU4M+/DNaduD+nkznlTIA3u3obKFoh6Gyyf8L2Hwo4fikrt5IUr2gJFQfkPdEe4TtyPco9aQgd/udRrYXCS8Xcd9AZsCBJR50gXtM=
    - secure: pE1VDNOQ00bll9VEIsIiWuAruTS7/++jv3ERXrtT/9M/XZRN+4bF2uY4IIPs5D+YnWD+wVgeBWeC3QGFxcaYmnwkvS+ZkNb7OCpINXvVkoHyT1DWQKzf4S9AtelWiJwpJ3fwEx8UdqaUUtgS34+ifHc/EcpHcbfbOhd5bZ3JEtOc+D/tE/G/+wBRrZOvs/NSpTpTxTFZGHKSQDosrslffJgfwT3ySN0HpighfbaDeTWeDCu2+bGzPtgVf38yqlPiBav5xdZF+yZvdp/1aQzVDX+KwxASZlMwBeqHaLXQbOQ7Iph/DJc64q5tzWULQDwn0trgFtBsOIzbQvFAV8AFoqKFth7JBrM+aa5/Lw2AIhs0yLCBA6/dc5GOJqmeyHMlbL9k1dw7J5Kd0i0uTP8/4Po7ZAQNZtWGcM7G9n3v2xok8p2MRfPSxDpwR8v+uDGpQa0mEyQGRSFGw0PtUQUr34Mn4lTg98JbJzs24D2gEEUBtbPdwmekfDWMdRoJA2ltsuj5bWvu/RYgAkbfnrWziTBkiaxW7NBbCykmjTCnIG2fEEHmy/pbAnu1TFC1XC+laQCCXekR435TAZacZYMcdGuMkZk+PWhwvNalBAJtVeg+Nj7x50H7vnAa8ONEjeNAUBaBUxUPdoW1rLagnPoz9aZ7O+JtKjHApe4LdJnjwEM=
