# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test and Release

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup gcloud environment
        uses: GoogleCloudPlatform/github-actions@0.1.2
        with:
          # The service account key which will be used for authentication.
          service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10'

      - run: npm ci

      - name: Dotenv Action
        id: dotenv
        uses: falti/dotenv-action@v0.2.4
        with:
          path: ci.env

      - run: npm run build
        env:
          NODE_ASSET_VERSION: ${{ steps.dotenv.outputs.node_asset_version }} # https://bit.ly/3077KHm
          NODE_BUCKET_NAME: ${{ steps.dotenv.outputs.node_bucket_name }}

      - run: npx semantic-release
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # https://bit.ly/3cllYHl
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload to Bucket
        if: github.ref == 'refs/branches/master' || startsWith(github.ref, 'refs/branches/release')
        run: |
          gsutil -m -h "Cache-Control:public, max-age=3600" cp -r dist gs://$NODE_BUCKET_NAME
        env:
          NODE_BUCKET_NAME: ${{ steps.dotenv.outputs.node_bucket_name }}

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://spr.hackforplay.xyz/?seed=assets
          SLACK_USERNAME: 'assets ボット'
